name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build menu-service
      run: |
        cd menu-service.zip_expanded/menu-service
        mvn clean install -DskipTests=false

    - name: Build order-service
      run: |
        cd order-service.zip_expanded/order-service
        mvn clean install -DskipTests=false
