name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Build eureka-server
      run: |
        cd eureka-server.zip_expanded/eureka-server
        mvn clean install -DskipTests=false
        
    - name: Build api-gateway
      run: |
        cd api-gateway.zip_expanded/api-gateway
        mvn clean install -DskipTests=false
        
    - name: Build user-service
      run: |
        cd user-service.zip_expanded/user-service
        mvn clean install -DskipTests=false

    - name: Build menu-service
      run: |
        cd menu-service.zip_expanded/menu-service
        mvn clean install -DskipTests=false

    - name: Build order-service
      run: |
        cd order-service.zip_expanded/order-service
        mvn clean install -DskipTests=false
        
    - name: Build notification-service
      run: |
        cd notification-service.zip_expanded/notification-service
        mvn clean install -DskipTests=false
        
    - name: Upload user-service JAR
      uses: actions/upload-artifact@v4
      with:
        name: user-service
        path: user-service.zip_expanded/user-service/target/*.jar
